name: pio run test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install python
      uses: actions/setup-python@v1
      with:
          python-version: 3.7
    - name: install runner
      run: |
        python -mpip install platformio
        echo '#!/bin/bash' > run.sh
        echo 'set -e -o pipefail' >> run.sh
        echo 'platformio run --verbose --environment $1' >> run.sh
        chmod +x run.sh
    - name: run things
      run: |
        mkdir cache
        find cache > empty.list
        ./run.sh one
        mv cache cache_one
        ./run.sh two
        mv cache cache_two
        (diff -sru cache_one cache_two || true) > cache_one_vs_cache_two.diff
        rm -rf .pio/build/one
        ./run.sh one
        (diff -sru cache_one cache || true) > cache_one_vs_cache_one.diff
    - name: show diffs
      run: |
        echo "1vs2  -----------------"
        cat cache_one_vs_cache_two.diff
        echo "1vs1(again)-----------------"
        cat cache_one_vs_cache_one.diff
