name: pio run test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install python
      uses: actions/setup-python@v1
      with:
          python-version: 3.7
    - name: install runner
      run: |
        python -mpip install platformio
        echo '#!/bin/sh' > run.sh
        echo 'set -e -o pipefail' >> run.sh
        echo 'platformio run --verbose --environment $1 | grep -E "Retrieved|Compiling"' >> run.sh
        chmod +x run.sh
    - name: run things the first time
      run: |
        mkdir cache
        find cache > empty.list
        ./run.sh one
        find cache > after_one_1.list
        diff -u empty.list after_one_1.list || true
        ./run.sh two
        find cache > after_two_1.list
        diff -u after_one_1.list after_two_1.list || true
    - name: run things again
      run: |
        ./run.sh one
        find cache > after_one_2.list
        diff -u after_two_1.list after_one_1.list || true
        ./run.sh two
        find cache > after_two_2.list
        diff -u after_one_2.list after_two_2.list || true
    - name: remove build dir and run
      run: |
        rm -rf .pio/build/
        ./run.sh one
        find cache > after_one_3.list
        diff -u after_two_2.list after_one_3.list || true
        ./run.sh two
        find cache > after_two_3.list
        diff -u after_one_3.list after_two_3.list || true
