name: pio run test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install python
      uses: actions/setup-python@v1
      with:
          python-version: 3.7
    - name: install runner
      run: |
        python -mpip install platformio
        echo '#!/bin/bash' > run.sh
        echo 'set -e -o pipefail' >> run.sh
        echo 'platformio run --verbose --environment $1 | grep -E "Retrieved|xtensa-esp32-elf"' >> run.sh
        chmod +x run.sh
    - name: run things
      run: |
        mkdir cache
        find cache > empty.list
        ./run.sh one
        mv cache cache_one
        ./run.sh two
        diff -ru cache_one cache || true
        rm -rf .pio/build/one
        ./run.sh one
        diff -ru cache_one cache || true
